# clan_territorial_simulation/config.py
GRID_SIZE = (100, 100)
INITIAL_CLAN_COUNT = 5
MIN_CLAN_SIZE = 5
MAX_CLAN_SIZE = 20
RESOURCE_MAX = 100.0
RESOURCE_REGENERATION_RATE = 0.05
RESOURCE_REQUIRED_PER_INDIVIDUAL = 0.1
MORTALITY_STARVATION_MAX = 0.5

# Parámetros de Validación
CONVERGENCE_DTS = [0.1, 0.05, 0.025]
CONVERGENCE_STEPS = 100
MONTE_CARLO_RUNS = 10
MONTE_CARLO_STEPS = 50